---
# tasks file for cron
- name: include assert.yml
  include_tasks: assert.yml

- name: install cron
  package:
    name: "{{ cron_packages }}"
    state: present

- name: start and enable cron
  service:
    name: "{{ cron_service }}"
    state: started
    enabled: yes
  when:
    - cron_service | length

- name: schedule requested cron jobs
  cron:
    name: "{{ item.name }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    job: "{{ item.job }}"
    state: "{{ item.state | default('present') }}"
    user: "{{ item.user | default(omit) }}"
  loop: "{{ cron_jobs }}"
  notify:
    - restart cron
  when:
    - cron_jobs is defined
