#!/usr/bin/env ansible-playbook
---
- name: create machines
  hosts: localhost
  gather_facts: no

  tasks:
    - name: apply terraform code
      terraform:
        project_path: ./terraform
        state: present
        force_init: yes
      register: terraform

    - name: add terraform hosts to inventory
      add_host:
        name: "{{ terraform.outputs.name.value }}"
        groups:
          - rancher

    - name: wait a moment to allow dns updates
      pause:
        seconds: 15

- name: setup rancher node
  hosts: all
  become: no
  gather_facts: no
  remote_user: root

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.buildtools
    - role: robertdebock.epel
    - role: robertdebock.python_pip
    - role: robertdebock.docker_ce

  tasks:
    - name: create rancher server container
      docker_container:
        name: rancher
        image: rancher/rancher
        restart_policy: unless-stopped
        privileged: yes
        ports:
          - "80:80"
          - "443:443"

    - name: wait for rancher to become available
      wait_for:
        # host: "{{ inventory_hostname }}"
        port: 443

    - name: show rancher endpoint
      debug:
        msg: "Rancher is installed at https://{{ inventory_hostname }}/"
