#!/usr/bin/env ansible-playbook
---
- name: create machines
  hosts: localhost
  gather_facts: no

  tasks:
    - name: apply terraform code
      terraform:
        project_path: ./terraform
        state: present
      register: terraform

    - name: add terraform hosts to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - rancher
      loop: "{{ terraform.outputs.name.value }}"

    - name: wait a moment to allow dns updates
      pause:
        seconds: 15

- name: setup rancher node
  hosts: all
  become: yes
  gather_facts: no
  remote_user: root

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.hostname
    - role: robertdebock.buildtools
    - role: robertdebock.python_pip
    - role: robertdebock.cron
    - role: robertdebock.ntp
    - role: robertdebock.grub
      grub_options:
        - option: systemd.unified_cgroup_hierarchy
          value: 0
    - role: robertdebock.docker

  post_tasks:
    - name: run grubby
      command: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
      notify:
        - reboot

    - name: flush handlers
      meta: flush_handlers

    - name: create rancher server container
      docker_container:
        name: rancher
        image: rancher/rancher
        restart_policy: always
        privileged: yes
        ports:
          - "80:80"
          - "443:443"

    - name: show rancher endpoint
      debug:
        msg: "Rancher is installed at https://{{ ansible_fqdn }}/"

  handlers:
    - name: reboot
      reboot:
