---

- name: test if ntp_interfaces is set correctly
  assert:
    that:
      - ntp_interfaces is defined
      - ntp_interfaces is iterable
    quiet: yes

- name: test if item in ntp_interfaces is set correctly
  assert:
    that:
      - item.address is defined
      - item.address is string
    quiet: yes
  loop: "{{ ntp_interfaces }}"
  loop_control:
    label: "{{ item.address }}"

- name: test if ntp_pool is set correctly
  assert:
    that:
      - ntp_pool is defined
      - ntp_pool is iterable
    quiet: yes

- name: test if item in ntp_pool is set correctly
  assert:
    that:
      - item.name is defined
      - item.name is string
    quiet: yes
  loop: "{{ ntp_pool }}"
  loop_control:
    label: "{{ item.name }}"

- name: test if ntp_server is set correctly
  assert:
    that:
      - ntp_server is iterable
    quiet: yes
  when:
    - ntp_server is defined

- name: test if item in ntp_server is set correctly
  assert:
    that:
      - item.name is defined
      - item.name is string
    quiet: yes
  when:
    - ntp_server is defined

- name: test if ntp_timezone is set correctly
  assert:
    that:
      - ntp_timezone is defined
      - ntp_timezone is string
    quiet: yes
