---
# tasks file for ntp
- name: include assert.yml
  include_tasks: assert.yml

- name: install {{ ntp_packages }}
  package:
    name: "{{ ntp_packages }}"
    state: present
  register: ntp_install_ntp
  until: ntp_install_ntp is succeeded
  retries: 3

- name: configure /etc/{{ ntp_configuration_file }}
  template:
    src: "{{ ntp_configuration_file }}.j2"
    dest: /etc/{{ ntp_configuration_file }}
  notify:
    - restart ntp/chrony

- name: install timezone information
  package:
    name: "{{ ntp_timezone_packages }}"
    state: present
  register: ntp_install_timezone_information
  until: ntp_install_timezone_information is succeeded
  retries: 3

- name: configure timezone
  timezone:
    name: "{{ ntp_timezone }}"
  when:
    - ntp_timezone_supported | bool
  notify:
    - restart cron

- name: start and enable {{ ntp_service }}
  service:
    name: "{{ ntp_service }}"
    state: started
    enabled: yes
