galaxy_info:
  author: Robert de Bock
  role_name: ntp
  description: Install and configure ntp on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.8

  platforms:
    - name: Amazon
      versions:
        - 2018.03
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Fedora
      versions:
        - 31
        - 32
    - name: Ubuntu
      versions:
        - focal
        - bionic
        - xenial

  galaxy_tags:
    - ntp
    - ntpd
    - ntpdate
    - centos

dependencies: []
