---
# vars file for cron
_cron_packages:
  default:
    - cronie
  Alpine:
    - dcron
  Debian:
    - cron

cron_packages: "{{ _cron_packages[ansible_os_family] | default(_cron_packages['default']) }}"

_cron_service:
  default: crond
  Alpine: '[]'
  Debian: cron
  Suse: cron

cron_service: "{{ _cron_service[ansible_os_family] | default(_cron_service['default']) }}"
