galaxy_info:
  author: Robert de Bock
  role_name: core_dependencies
  description: Install dependecies to support the Ansible core modules.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.8

  platforms:
    - name: Alpine
      versions:
        - all
    - name: Amazon
      versions:
        - 2018.03
    - name: EL
      versions:
        - 7
        - 8
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Fedora
      versions:
        - 31
        - 32
    - name: OpenSUSE
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - bionic
        - xenial

  galaxy_tags:
    - coredependencies
    - centos
    - redhat

dependencies: []
