galaxy_info:
  author: Robert de Bock
  role_name: grub
  description: Configure grub on your system.
  license: Apache-2.0
  company: none
  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - 31
        - 32
    - name: Ubuntu
      versions:
        - bionic

  galaxy_tags:
    - grub
    - centos
    - redhat

dependencies: []
