---
# tasks file for hostname
- name: install requirements
  package:
    name: "{{ hostname_requirements }}"
    state: present
  register: hostname_install_requirements
  until: hostname_install_requirements is succeeded
  retries: 3

- name: set hostname
  hostname:
    name: "{{ hostname }}"
  when:
    - ansible_connection != "docker"
  register: hostname_set_hostname

- name: reboot for hostname
  include_role:
    name: robertdebock.reboot
  when:
    - hostname_set_hostname.changed
    - hostname_reboot | bool
  tags:
    - skip_ansible_lint
