---
# tasks file for hostname
- name: include assert.yml
  include_tasks: assert.yml

- name: install requirements
  package:
    name: "{{ hostname_requirements }}"
    state: present

- name: set hostname
  hostname:
    name: "{{ hostname }}"
  notify:
    - reboot
  when:
    - ansible_connection != "docker"
